[package]
name = "fonda"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
fs2 = "0.4.3"
tokio = { version = "1", features = ["full"] }