name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fonda
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./fonda
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: fonda
          target: ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}